### PR TITLE
 Include src/LittleHalHost.Example/Example.csproj from yreynhout's gist

### PR DESCRIPTION
**Pull request by michael-freidgeim-webjet**
Added LittleHalHost.Example/Example.csproj and readme.md describing url parameters

### CODE REVIEW

**Comment by michael-freidgeim-webjet** [comment]
I am not sure why The Travis CI build failed 

>  error MSB3202: The project file "/src/LittleHalHost.Example/Example.csproj" was not found. [/src/SqlStreamStore.HAL.sln]  

The file src/LittleHalHost.Example/Example.csproj has been added to git and Visual Studio builds the solution successfully

**Comment by thefringeninja** [comment]
The issue is here: https://github.com/SQLStreamStore/SQLStreamStore.HAL/blob/master/Dockerfile#L8

The `Dockerfile` is assuming that the folder name and the project file name are the same.

**Comment by MNF** [comment]
Do you mean squash commits similar to 
https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/ ?

**Comment by thefringeninja** [comment]
Squashing is up to you, but you should definitely rebase it. I don't like back merges 😄

**Comment by michael-freidgeim-webjet** [comment]
Resubmitted as single commit   https://github.com/SQLStreamStore/SQLStreamStore.HAL/pull/30

**Pull request closed without merging**
